### ISSUE TITLE
about baseline score

### ISSUE THREAD

**Issue by everks** [jianguoz/Few-Shot-Intent-Detection#3]
I wonder where the baseline score came from? I don't find the corresponding score in the original paper, and the reproducible experiment results are quite different from that. For example, the Roberta-classifier performance on   clinc 5-shot is much lower than the score here cause it is just a simple RobertaForSequenceClassification call. I don't think my code is wrong. Can you please tell me where the score comes from?

**Comment by jianguoz** [comment]
@everks Which baselines score are you targeting? The Roberta-classifier baseline score is reported by [DNNC](https://github.com/salesforce/DNNC-few-shot-intent). The intent accuracy is when the threshold is set to 0 in the paper, and based on the [DNNC code](https://github.com/salesforce/DNNC-few-shot-intent/blob/master/train_classifier.py), the RoBERTa-classifier performs reasonably well.

**Comment by everks** [comment]
I am sorry, but I look through the paper again and don't find any experiments about BANKING77 and HWU64.

**Comment by jianguoz** [comment]
@everks Yes, you are right. They are not reported on the DNNC paper. We asked the authors (I am also one author of the DNNC paper) to provide numbers on the additional two datasets. Sorry that I did not state it clearly in the previous reply.
