### ISSUE TITLE
BANKING77-OOS: train split in id-oos

### ISSUE THREAD

**Issue by mebrunet** [jianguoz/Few-Shot-Intent-Detection#7]
In Table 3 of your [paper](https://arxiv.org/abs/2106.04564), you mark that there are no out-out-scope (oos) training examples for the modified CLINC150 and BANKING77 challenge sets you created and released in this repository. However, in this repository, BANKING77-OOS has a train split in the id-oos folder. Are those intended to be used for training the models? For example, were they used to train the models whose results are reported in table 4?

**Comment by jianguoz** [comment]
Hi @mebrunet, thanks for raising the question! BANKING77-OOS indeed has a training split in the id-oos folder. We did not use the train split of id-oos to train the models in Table 4. We keep the train split for researchers who want to train models with added id-oos examples.  
Besides, thanks for pointing out the mismatch in Table 3, and we will update the paper in the next version.
